# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Simon Ellice
description: >- # this means to ignore newlines until "baseurl:"
  Noir Crime Thriller Series
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://simonellice.co.uk"

instagram: simonellice13
facebook: simonelliceuk

# Collections
collections_dir: gun_room
collections:
    glossary:
        output: true
    character:
        output: true
    place:
        output: true
    item:
        output: true

# Specify default template for collections
defaults:
  - scope:
      path: ""
      type: "glossary"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "character"
    values:
      layout: "character"
  - scope:
      path: ""
      type: "place"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "item"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
